name: Releases

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4.3.1
        with:
          gradle-version: 8.13
        name: Set up Gradle
      - name: Add permission
        run: chmod +x ./gradlew
      - name: Execute Gradle build
        run: ./gradlew build

      - uses: ncipollo/release-action@v1.16.0
        with:
          artifacts: "build/libs/*"
          generateReleaseNotes: true
